version: "3"

networks:
  mongo:

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
    networks:
      - mongo
    ports:
      - 27028:27017

  clean-code:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
    networks:
      - mongo
    env_file: .env
    ports:
      - 3000:3000
    environment:
      MONGO_URI: ${MONGO_URI}
